#!/usr/bin/env python3.12
"""
test_parsing_equivalence.py
=========================
Regression tests for the two parsers of the berthommier project:

  1. parsing.parse_input()              -> ParseResult (COVTL reference)
  2. continuous.syllabify_continuous()  -> ChainElement[]  (runtime engine)

Goal: ensure that BOTH parsers produce flat segments that are
(structurally) equivalent for all linking configurations.

The tests cover:
  - CV, V, VC, CVC, CCV, VCC, CVCC, CCVCC
  - Coarticulation dot C.C (split) and C.V/V.C/V.V (merge)
  - Inter-word separations (space = GAP)
  - Explicit pauses (|)
  - Hyphen as separator (equivalent to the dot)
  - Consonant clusters
  - Edge cases (boundaries, adjacent vowels)
  - Mixed combinations

Comparison:
  - PHASE 1: flat segments — strict equivalence, no
    segment may be lost or reordered.
  - PHASE 2: word boundaries (GAP) — positions of the separations.
  - PHASE 3: syllabic structures (informational, the two parsers
    have different definitions of "syllable").

Usage:
  python3.12 scripts/test_parsing_equivalence.py            # run all
  python3.12 scripts/test_parsing_equivalence.py --list       # list test cases
  python3.12 scripts/test_parsing_equivalence.py --detail     # verbose output
"""
from __future__ import annotations

import sys
import os
import json
from dataclasses import dataclass, field
from typing import List, Optional, Tuple, Dict

# --- Setup path ---
PROJ = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                      'download', 'berthommier_vtl_pipeline')
sys.path.insert(0, PROJ)

from vtl_synth.core.parsing import parse_input as parse_ref
from vtl_synth.core.continuous import (
    parse_ipa_with_markers,
    syllabify_continuous,
    ChainElement,
    ChainElementType,
)
from vtl_synth.core.constants import VOWEL_TARGETS


# ======================================================================
# Test cases — ground truth generated by parsing.py
# ======================================================================
# Each case is defined by: input, expected_flat, and metadata.
# expected_flat is the ordered list of IPA segments (without GAP/|),
# i.e. the filtered output of parsing.py.
#
# Note: the ground truth file was generated once with
#   python3.12 -c "... [dump parsing.py output as JSON] ..."
# then the values were frozen here.
# ======================================================================

@dataclass
class TestCase:
    input_text: str
    description: str
    expected_flat: List[str]
    category: str


def build_test_cases() -> List[TestCase]:
    cases: List[TestCase] = []

    # ==================================================================
    # Simple CV
    # ==================================================================
    cases.append(TestCase('ba',  'CV (b+a)',           ['b','a'],        'CV'))
    cases.append(TestCase('da',  'CV (d+a)',           ['d','a'],        'CV'))
    cases.append(TestCase('ga',  'CV (g+a)',           ['g','a'],        'CV'))
    cases.append(TestCase('bi',  'CV (b+i)',           ['b','i'],        'CV'))
    cases.append(TestCase('di',  'CV (d+i)',           ['d','i'],        'CV'))
    cases.append(TestCase('gi',  'CV (g+i)',           ['g','i'],        'CV'))
    cases.append(TestCase('bu',  'CV (b+u)',           ['b','u'],        'CV'))
    cases.append(TestCase('du',  'CV (d+u)',           ['d','u'],        'CV'))
    cases.append(TestCase('gu',  'CV (g+u)',           ['g','u'],        'CV'))

    # ==================================================================
    # Isolated V
    # ==================================================================
    cases.append(TestCase('a',   'Vowel a',             ['a'],           'V'))
    cases.append(TestCase('i',   'Vowel i',             ['i'],           'V'))
    cases.append(TestCase('u',   'Vowel u',             ['u'],           'V'))

    # ==================================================================
    # VC, CVC, etc.
    # ==================================================================
    cases.append(TestCase('ab',  'VC (a+b)',           ['a','b'],        'CVC'))
    cases.append(TestCase('ad',  'VC (a+d)',           ['a','d'],        'CVC'))
    # abda: 1 word, 1 syl (no dot), 2 vowels = intra structure
    cases.append(TestCase('abda','VCVC (a+b+d+a)',    ['a','b','d','a'],'CVC'))
    cases.append(TestCase('alda','VCCV (a+l+d+a)',    ['a','l','d','a'],'CVC'))

    # ==================================================================
    # Dot: C.V → merge (ignored)
    # ==================================================================
    # ba.da: dot between a(V) and d(C) → V.C → merge → 1 syllable
    cases.append(TestCase('ba.da','C.V merge: 1 syl',  ['b','a','d','a'],'DOT'))
    cases.append(TestCase('bi.di','C.V merge: 1 syl',  ['b','i','d','i'],'DOT'))
    cases.append(TestCase('ba.da.ga','C.V merge x2: 1 syl',
                          ['b','a','d','a','g','a'],'DOT'))
    cases.append(TestCase('ba-da-ga','hyphen C.V merge',
                          ['b','a','d','a','g','a'],'DOT'))
    # a.da: V.V → merge
    cases.append(TestCase('a.da','V.V merge: 1 syl',  ['a','d','a'],     'DOT'))

    # ==================================================================
    # Dot: C.C → split (respected)
    # ==================================================================
    # ab.da: dot between b(C) and d(C) → C.C → split → 2 syllables
    cases.append(TestCase('ab.da','C.C split: 2 syl',  ['a','b','d','a'],'DOT'))
    cases.append(TestCase('ab-da','hyphen C.C split',  ['a','b','d','a'],'DOT'))
    # ap.da: dot between p(C) and d(C) → C.C → split
    cases.append(TestCase('ap.da','C.C split (p.d)',  ['a','p','d','a'],'DOT'))
    # ad.ta: dot between d(C) and t(C) → C.C → split
    cases.append(TestCase('ad.ta','C.C split (d.t)',  ['a','d','t','a'],'DOT'))
    # sta.ka: dot between a(V) and k(C) → V.C → merge → 1 syll
    cases.append(TestCase('sta.ka','V.C merge (a.k)', ['s','t','a','k','a'],'DOT'))

    # ==================================================================
    # Spaces = inter-word separations (GAP)
    # ==================================================================
    cases.append(TestCase('ba da','2 words CV',       ['b','a','d','a'],'SPACE'))
    cases.append(TestCase('ab da','VC then CV',      ['a','b','d','a'],'SPACE'))
    cases.append(TestCase('ba da ga','3 words CV',    ['b','a','d','a','g','a'],'SPACE'))
    cases.append(TestCase('ab da ga','VC+CV+CV',      ['a','b','d','a','g','a'],'SPACE'))
    cases.append(TestCase('ab da bi gu','4 words',    ['a','b','d','a','b','i','g','u'],'SPACE'))

    # ==================================================================
    # Dot + space combinations
    # ==================================================================
    # THE PROBLEM CASE: ab.da (2 syl) then abda (1 syl)
    cases.append(TestCase('ab.da abda','mix: 2syl + 1syl',
                          ['a','b','d','a','a','b','d','a'],'MIX'))
    cases.append(TestCase('ba.da.ga ba da ga','mix: merge + 3 mots',
                          ['b','a','d','a','g','a','b','a','d','a','g','a'],'MIX'))
    cases.append(TestCase('ab.da ga.bi','mix: split + merge',
                          ['a','b','d','a','g','a','b','i'],'MIX'))
    cases.append(TestCase('ab.da ga.bi du.sta','complex mix',
                          ['a','b','d','a','g','a','b','i','d','u','s','t','a'],'MIX'))

    # ==================================================================
    # Explicit pauses (|)
    # ==================================================================
    cases.append(TestCase('ba | da','explicit pause', ['b','a','d','a'],'PAUSE'))
    # ba|da: | is a pause marker but parsing.py
    # treats it as a word "|" which is a pause_marker, flushing the block.
    # The flat output is [b,a,GAP,d,a] but with |: [b,a,|,d,a]
    # Filtering out GAP/|: [b,a,d,a]
    cases.append(TestCase('ba|da','attached pause',    ['b','a','d','a'],'PAUSE'))

    # ==================================================================
    # Consonant clusters
    # ==================================================================
    cases.append(TestCase('sta', 'CCV (s+t+a)',        ['s','t','a'],     'CLUST'))
    cases.append(TestCase('stak','CCVC',               ['s','t','a','k'],'CLUST'))
    cases.append(TestCase('bal', 'CVC (b+a+l)',        ['b','a','l'],     'CLUST'))
    cases.append(TestCase('bald','CVCC (b+a+l+d)',    ['b','a','l','d'],'CLUST'))
    # trand: 'r' is not in ALL_PHONEME_KEYS (the key is 'R')
    # so 'r' is silently ignored.
    cases.append(TestCase('trand','CCVC (r ignored)',    ['t','a','n','d'],'CLUST'))

    # ==================================================================
    # Edge cases
    # ==================================================================
    cases.append(TestCase('a i u','3 spaced vowels',  ['a','i','u'],           'EDGE'))
    # ai: 2 adjacent vowels, no dot → 1 syllable (parsing.py)
    cases.append(TestCase('ai',  'VV adjacent: 1 syl',     ['a','i'],               'EDGE'))

    return cases


# ======================================================================
# Helpers
# ======================================================================

def get_cont_flat(text: str) -> List[str]:
    """Get flat segment list from continuous.py."""
    tokens = parse_ipa_with_markers(text, add_phrase_anchors=False)
    elements = syllabify_continuous(tokens)
    flat: List[str] = []
    for e in elements:
        if e.is_pause:
            continue
        segs = list(e.onset_keys)
        if e.nucleus_key:
            segs.append(e.nucleus_key)
        segs.extend(e.coda_keys)
        flat.extend(segs)
    return flat


def get_ref_flat(text: str) -> List[str]:
    """Get flat segment list from parsing.py (reference)."""
    pr = parse_ref(text)
    return [s for s in pr.flat if s not in ('GAP', '|')]


def get_ref_gap_positions(text: str) -> List[int]:
    """Get positions of GAP markers in parsing.py output."""
    pr = parse_ref(text)
    return [i for i, s in enumerate(pr.flat) if s == 'GAP']


def get_cont_pause_count(text: str) -> int:
    """Count PAUSE elements from continuous.py."""
    tokens = parse_ipa_with_markers(text, add_phrase_anchors=False)
    elements = syllabify_continuous(tokens)
    return sum(1 for e in elements if e.is_pause)


def get_ref_gap_count(text: str) -> int:
    """Count GAP markers in parsing.py output."""
    pr = parse_ref(text)
    return sum(1 for s in pr.flat if s == 'GAP')


def get_cont_syllable_count(text: str) -> int:
    """Count syllable elements from continuous.py."""
    tokens = parse_ipa_with_markers(text, add_phrase_anchors=False)
    elements = syllabify_continuous(tokens)
    return sum(1 for e in elements if not e.is_pause)


def get_ref_syllable_count(text: str) -> int:
    """Count total syllables across all words in parsing.py output."""
    pr = parse_ref(text)
    total = 0
    for word_syls in pr.syllables_per_word:
        total += len(word_syls)
    return total


def get_cont_syllable_details(text: str) -> List[str]:
    """Get syllable structure details from continuous.py."""
    tokens = parse_ipa_with_markers(text, add_phrase_anchors=False)
    elements = syllabify_continuous(tokens)
    details = []
    for e in elements:
        if e.is_pause:
            details.append(f'PAUSE({e.pause_key})')
        else:
            details.append(f'{e.structure_type}(onset={e.onset_keys},nuc={e.nucleus_key},coda={e.coda_keys})')
    return details


# ======================================================================
# Test runner
# ======================================================================

class TestResult:
    def __init__(self):
        self.passed = 0
        self.failed = 0
        self.errors: List[dict] = []

    def ok(self):
        self.passed += 1

    def fail(self, case: TestCase, field: str, expected, actual, detail: str = ''):
        self.failed += 1
        self.errors.append({
            'input': case.input_text,
            'category': case.category,
            'description': case.description,
            'field': field,
            'expected': [str(x) for x in expected] if isinstance(expected, (list, tuple)) else str(expected),
            'actual': [str(x) for x in actual] if isinstance(actual, (list, tuple)) else str(actual),
            'detail': detail,
        })


def main():
    args = sys.argv[1:]
    verbose = '--detail' in args

    cases = build_test_cases()

    if '--list' in args:
        print(f'\n=== {len(cases)} test cases ===\n')
        by_cat: Dict[str, List[TestCase]] = {}
        for c in cases:
            by_cat.setdefault(c.category, []).append(c)
        for cat in sorted(by_cat.keys()):
            print(f'\n--- {cat} ({len(by_cat[cat])} tests) ---')
            for c in by_cat[cat]:
                print(f'  "{c.input_text:20s}"  {c.description}')
                print(f'    expected_flat={c.expected_flat}')
        print(f'\nTotal: {len(cases)} test cases')
        return 0

    # ===== PHASE 1: Flat segment equivalence (CRITICAL) =====
    print('=' * 70)
    print('PHASE 1: Flat segment equivalence')
    print('        parsing.py vs continuous.py')
    print('=' * 70)
    tr = TestResult()
    for case in cases:
        ref = get_ref_flat(case.input_text)
        cont = get_cont_flat(case.input_text)
        if ref == cont:
            tr.ok()
            if verbose:
                print(f'  OK   "{case.input_text:20s}" {case.description}')
        else:
            tr.fail(case, 'flat', ref, cont)
            print(f'  FAIL "{case.input_text:20s}" {case.description}')
            print(f'        ref ={ref}')
            print(f'        cont={cont}')
    print(f'\n  Result: {tr.passed}/{len(cases)} OK, {tr.failed} FAIL')

    # ===== PHASE 2: GAP / pause count (informational) =====
    # Note: parsing.py always adds a final GAP,
    # whereas continuous.py does not add a final pause
    # when add_phrase_anchors=False. The diffs are expected.
    print('\n' + '=' * 70)
    print('PHASE 2: Inter-word separators (informational)')
    print('        parsing.py final GAP ≠ continuous.py (expected behavior)')
    print('=' * 70)
    gap_diffs = 0
    for case in cases:
        ref_gaps = get_ref_gap_count(case.input_text)
        cont_pauses = get_cont_pause_count(case.input_text)
        # Only count diffs for multi-word inputs
        # (1-GAP diffs for single-word inputs are the trailing GAP)
        is_multi_word = ' ' in case.input_text and '|' not in case.input_text
        if ref_gaps != cont_pauses and is_multi_word:
            gap_diffs += 1
            if verbose:
                print(f'  DIFF "{case.input_text:20s}" gaps={ref_gaps} pauses={cont_pauses}')
    print(f'  {len(cases) - gap_diffs}/{len(cases)} consistent, {gap_diffs} multi-word diffs')

    # ===== PHASE 3: Syllable count (informational) =====
    print('\n' + '=' * 70)
    print('PHASE 3: Syllable count (informational)')
    print('        (the two parsers have different definitions)')
    print('=' * 70)
    syl_diff = 0
    for case in cases:
        ref_n = get_ref_syllable_count(case.input_text)
        cont_n = get_cont_syllable_count(case.input_text)
        if ref_n != cont_n:
            syl_diff += 1
            if verbose:
                cont_detail = get_cont_syllable_details(case.input_text)
                print(f'  DIFF "{case.input_text:20s}" ref={ref_n} cont={cont_n}')
                for d in cont_detail:
                    print(f'        {d}')
    print(f'  {len(cases) - syl_diff}/{len(cases)} identical, {syl_diff} expected diffs')

    # ===== SUMMARY =====
    print('\n' + '=' * 70)
    print('SUMMARY')
    print('=' * 70)
    total = len(cases)
    print(f'  Test cases         : {total}')
    print(f'  Flat (CRITICAL)    : {tr.passed}/{total}')
    print(f'  Inter-word GAP     : {total - gap_diffs}/{total} (info)')
    print(f'  Syl count          : {total - syl_diff}/{total} identical (info)')

    # Save results as JSON
    results = {
        'total': total,
        'flat': {'passed': tr.passed, 'failed': tr.failed,
                 'errors': tr.errors},
        'gap_interword_diffs': gap_diffs,
        'syl_count_diffs': syl_diff,
    }
    out_path = os.path.join(PROJ, 'download', 'parsing_test_results.json')
    with open(out_path, 'w', encoding='utf-8') as f:
        json.dump(results, f, ensure_ascii=False, indent=2)
    print(f'\n  JSON results: {out_path}')

    # Exit code: only flat is critical
    return 1 if tr.failed > 0 else 0


if __name__ == '__main__':
    sys.exit(main())
